# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Serverless Framework and other packages
        run: |
          npm install -g serverless
          npm ci

      - name: Deploy to AWS (Dev)
        if: github.ref == 'refs/heads/dev'
        run: serverless deploy --stage dev

      - name: Deploy to AWS (Prod)
        if: github.ref == 'refs/heads/main'
        run: |
          npm ci
          serverless deploy --stage prod
